In [1]:
import pandas as pd

C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [2]:
sea_levels = pd.read_csv('./Datasets/25_Change_in_Mean_Sea_Levels.csv')
sea_levels.head()

,Country,ISO2,ISO3,Indicator,Unit,Source,CTS Code,CTS Name,CTS Full Descriptor,Measure,Date,Value
0,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Arabian Sea,D10/17/1992,-62.65
1,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Atlantic Ocean,D10/17/1992,2.94
2,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Bay Bengal,D10/17/1992,9.81
3,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Bering Sea,D10/17/1992,33.77
4,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Caribbean Sea,D10/17/1992,75.22

In [3]:
#print(sea_levels.dtypes)
dates = sea_levels['Date'].str.split('/', expand = True)
sea_levels['Year'] = dates[2]
sea_levels.head()

,Country,ISO2,ISO3,Indicator,Unit,Source,CTS Code,CTS Name,CTS Full Descriptor,Measure,Date,Value,Year
0,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Arabian Sea,D10/17/1992,-62.65,1992
1,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Atlantic Ocean,D10/17/1992,2.94,1992
2,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Bay Bengal,D10/17/1992,9.81,1992
3,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Bering Sea,D10/17/1992,33.77,1992
4,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Caribbean Sea,D10/17/1992,75.22,1992

In [5]:
sea_levels = sea_levels.drop(columns = ['ISO2', 'ISO3', 'Indicator', 'Unit', 'Source', 'CTS Code', 'CTS Name', 'CTS Full Descriptor', 'Date']).reset_index()
sea_levels.head()

   index Country         Measure  Value  Year
0      0   World     Arabian Sea -62.65  1992
1      1   World  Atlantic Ocean   2.94  1992
2      2   World      Bay Bengal   9.81  1992
3      3   World      Bering Sea  33.77  1992
4      4   World   Caribbean Sea  75.22  1992

In [6]:
#creating only the world average
avg_sea_levels = sea_levels.drop(columns = ['Measure','index'])
avg_sea_level = avg_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level.head()

   Year Country      Value
0  1992   World  12.760722
1  1993   World -22.556941
2  1994   World -15.986588
3  1995   World  -6.315064
4  1996   World  -8.251323

In [7]:
#getting average for US
cols = ['Atlantic Ocean','Pacific Ocean', 'North Atlantic']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'United States'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for China
cols = ['South China','Yellow Sea']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'China, P.R.: Mainland'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for India
cols = ['Arabian Sea','Andaman Sea', 'Indian Ocean', 'Bay Bengal']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'India'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Philippines
cols = ['South China', 'Pacific Ocean']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Philippines'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Indonesia
cols = ['Atlantic Ocean','Pacific Ocean']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Indonesia'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Bangladesh
cols = ['Bay Bengal']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Bangladesh'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Vietnam
cols = ['Pacific Ocean','South China']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Vietnam'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Mexico
cols = ['Gulf Mexico','Pacific Ocean', 'Caribbean Sea']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Mexico'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Japan
cols = ['Sea Japan', 'Sea Okhotsk','Pacific Ocean']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Japan'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Brazil
cols = ['Atlantic Ocean']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Brazil'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Australia
cols = ['Southern Ocean','Pacific Ocean', 'Indian Ocean']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Australia'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for France
cols = ['Atlantic Ocean','North Sea', 'Mediterranean']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'France'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Pakistan
cols = ['Arabian Sea']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Pakistan'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Russian Federation
cols = ['Atlantic Ocean','Baltic Sea', ]
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Russian Federation'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Thailand
cols = ['Andaman Sea', 'Indian Ocean']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Thailand'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Colombia
cols = ['Caribbean Sea','Pacific Ocean']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Colombia'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Afghanistan
cols = ['Arabian Sea']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Afghanistan'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Peru
cols = ['Pacific Ocean']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Peru'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Canada
cols = ['Atlantic Ocean','Pacific Ocean', 'North Atlantic']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Canada'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Haiti
cols = ['Atlantic Ocean','Caribbean Sea']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Haiti'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Iran
cols = ['Persian Gulf']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Iran'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Italy
cols = ['Mediterranean']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Italy'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Sri Lanka
cols = ['Indian Ocean']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Sri Lanka'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for South Africa
cols = ['Atlantic Ocean','Southern Ocean','Indian Ocean']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'South Africa'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Argentina
cols = ['Atlantic Ocean']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Argentina'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Korea
cols = ['Sea of Japan','Yellow Sea']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Korea'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Nepal
cols = ['Indian Ocean','Bay Bengal']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Nepal'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for United Kingdom
cols = ['Atlantic Ocean','North Sea']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'United Kingdom'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Spain
cols = ['Atlantic Ocean','Mediterranean']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Spain'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

#getting average for Malaysia
cols = ['Andaman Sea', 'Indian Ocean', 'South China']
temp_sea_levels = sea_levels.loc[sea_levels['Measure'].isin(cols), :].reset_index()
temp_sea_levels = temp_sea_levels.drop(columns = ['Measure','level_0', 'index'])
temp_sea_levels['Country'] = 'Malaysia'
temp_sea_levels = temp_sea_levels.groupby(['Year', 'Country']).mean().reset_index()
avg_sea_level = pd.concat([avg_sea_level,temp_sea_levels])
print(avg_sea_level.shape)

(66, 3)
(99, 3)
(132, 3)
(165, 3)
(198, 3)
(231, 3)
(264, 3)
(297, 3)
(330, 3)
(363, 3)
(396, 3)
(429, 3)
(462, 3)
(495, 3)
(528, 3)
(561, 3)
(594, 3)
(627, 3)
(660, 3)
(693, 3)
(726, 3)
(759, 3)
(792, 3)
(825, 3)
(858, 3)
(891, 3)
(924, 3)
(957, 3)
(990, 3)
(1023, 3)

In [8]:
avg_sea_level.to_csv('./clean data/country_sea_levels.csv', index = False)