In [1]:
import pandas as pd

C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [10]:
df = pd.read_csv("./Datasets/Forest and carbon world only.csv")

In [11]:
df.columns

Index(['Unnamed: 0', 'ISO2', 'ISO3', 'Indicator', 'Unit', 'Source', 'CTS Code',
       'CTS Name', 'CTS Full Descriptor', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022'],
      dtype='object')

In [12]:
df

,Unnamed: 0,ISO2,ISO3,Indicator,Unit,Source,CTS Code,CTS Name,CTS Full Descriptor,1992,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,World,NaN,WLD,Carbon stocks in forests,Million tonnes,Food and Agriculture Organization of the Unite...,ECMFC,NaN,"Environment, Climate Change, Mitigation, Fores...",2.969488e+05,...,2.941946e+05,2.943746e+05,2.945546e+05,2.947507e+05,2.944740e+05,2.944503e+05,2.942958e+05,2.941356e+05,NaN,NaN
1,World,NaN,WLD,Forest area,1000 HA,Food and Agriculture Organization of the Unite...,ECMFF,NaN,"Environment, Climate Change, Mitigation, Fores...",4.220757e+06,...,4.092844e+06,4.088354e+06,4.083864e+06,4.080600e+06,4.073753e+06,4.068920e+06,4.063831e+06,4.058918e+06,4.053893e+06,4.048942e+06
2,World,NaN,WLD,Index of carbon stocks in forests,Index,Food and Agriculture Organization of the Unite...,ECMFS,NaN,"Environment, Climate Change, Mitigation, Fores...",1.000000e+02,...,9.907248e+01,9.913310e+01,9.919371e+01,9.925976e+01,9.916659e+01,9.915860e+01,9.910657e+01,9.905263e+01,NaN,NaN
3,World,NaN,WLD,Index of forest extent,Index,Food and Agriculture Organization of the Unite...,ECMFE,NaN,"Environment, Climate Change, Mitigation, Fores...",1.000000e+02,...,9.696943e+01,9.686305e+01,9.675667e+01,9.667934e+01,9.651714e+01,9.640261e+01,9.628204e+01,9.616564e+01,9.604659e+01,9.592930e+01

In [13]:
# Define the columns to keep
columns_to_keep = ['Indicator', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', 
                   '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', 
                   '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020','2021','2022']

In [14]:
# Filter the DataFrame to keep only the specified columns
df_filtered = df[columns_to_keep]

In [16]:
# Display the first few rows of the filtered DataFrame
df_filtered.head()

,Indicator,1992,1993,1994,1995,1996,1997,1998,1999,2000,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Carbon stocks in forests,2.969488e+05,2.967239e+05,2.964990e+05,2.962741e+05,2.960492e+05,2.958243e+05,2.955994e+05,2.953745e+05,2.951496e+05,...,2.941946e+05,2.943746e+05,2.945546e+05,2.947507e+05,2.944740e+05,2.944503e+05,2.942958e+05,2.941356e+05,NaN,NaN
1,Forest area,4.220757e+06,4.212918e+06,4.205080e+06,4.197241e+06,4.189403e+06,4.181565e+06,4.173726e+06,4.165888e+06,4.158050e+06,...,4.092844e+06,4.088354e+06,4.083864e+06,4.080600e+06,4.073753e+06,4.068920e+06,4.063831e+06,4.058918e+06,4.053893e+06,4.048942e+06
2,Index of carbon stocks in forests,1.000000e+02,9.992426e+01,9.984853e+01,9.977279e+01,9.969705e+01,9.962132e+01,9.954558e+01,9.946984e+01,9.939410e+01,...,9.907248e+01,9.913310e+01,9.919371e+01,9.925976e+01,9.916659e+01,9.915860e+01,9.910657e+01,9.905263e+01,NaN,NaN
3,Index of forest extent,1.000000e+02,9.981429e+01,9.962858e+01,9.944287e+01,9.925716e+01,9.907145e+01,9.888574e+01,9.870003e+01,9.851432e+01,...,9.696943e+01,9.686305e+01,9.675667e+01,9.667934e+01,9.651714e+01,9.640261e+01,9.628204e+01,9.616564e+01,9.604659e+01,9.592930e+01

In [17]:
# Assuming df_filtered is your current DataFrame
# Pivot the DataFrame
df_pivoted = df_filtered.pivot_table(values=['1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', 
                                             '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', 
                                             '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', 
                                             '2019', '2020','2021','2022'], 
                                     index='Indicator', 
                                     aggfunc='first').transpose()

In [18]:
# Reset the index to make the years a column
df_pivoted.reset_index(inplace=True)

In [19]:
df_pivoted.rename(columns={'index': 'Year'}, inplace=True)

In [20]:
# Display the first few rows of the pivoted DataFrame
df_pivoted

Indicator,Year,Carbon stocks in forests,Forest area,Index of carbon stocks in forests,Index of forest extent
0,1992,296948.8291,4220756.642,100.000000,100.000000
1,1993,296723.9289,4212918.252,99.924263,99.814289
2,1994,296499.0290,4205079.862,99.848526,99.628579
3,1995,296274.1290,4197241.472,99.772789,99.442868
4,1996,296049.2285,4189403.083,99.697052,99.257158
5,1997,295824.3288,4181564.692,99.621315,99.071447
6,1998,295599.4295,4173726.302,99.545578,98.885737
7,1999,295374.5288,4165887.912,99.469841,98.700026
8,2000,295149.6290,4158049.522,99.394104,98.514316
9,2001,295000.1375,4152876.264,99.343762,98.391749
10,2002,294850.6476,4147703.007,99.293420,98.269182
11,2003,294701.1574,4142529.749,99.243078,98.146614
12,2004,294551.6671,4137356.491,99.192736,98.024047
13,2005,294402.1767,4132183.233,99.142394,97.901480
14,2006,294252.6864,4127009.975,99.092051,97.778913
15,2007,294103.1955,4121836.718,99.041709,97.656346
16,2008,293953.7052,4116663.460,98.991367,97.533779
17,2009,293804.2152,4111490.202,98.941025,97.411212
18,2010,293654.7250,4106316.944,98.890683,97.288645
19,2011,293834.6057,4101823.291,98.951259,97.182179
20,2012,294014.5940,4097333.397,99.011872,97.075803
21,2013,294194.5829,4092843.503,99.072485,96.969426
22,2014,294374.5721,4088353.610,99.133097,96.863050
23,2015,294554.5616,4083863.716,99.193710,96.756673
24,2016,294750.6810,4080599.782,99.259755,96.679343
25,2017,294474.0169,4073753.425,99.166586,96.517136
26,2018,294450.3036,4068919.514,99.158601,96.402609
27,2019,294295.8080,4063830.760,99.106573,96.282044
28,2020,294135.6234,4058917.720,99.052629,96.165642
29,2021,NaN,4053892.727,NaN,96.046588
30,2022,NaN,4048942.374,NaN,95.929302

In [21]:
# Save the pivoted DataFrame to a CSV file
df_pivoted.to_csv("./clean data/Forest and Carbon_cleaned.csv", index=False)