In [1]:
import pandas as pd

C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [2]:
# Load the original dataset
df_original = pd.read_csv("./Datasets/Land Cover Accounts top 30.csv")

In [4]:
# Select the required columns
columns_required = ['Country', 'Indicator', 'Climate Influence', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020']
df_selected = df_original[columns_required]

In [5]:
# Merge 'Indicator' and 'Climate_Influence' columns and remove the originals
df_selected['Indicator and Influence'] = df_selected['Indicator'] + ": " + df_selected['Climate Influence']
df_selected.drop(['Indicator', 'Climate Influence'], axis=1, inplace=True)

C:\Users\noorh\AppData\Local\Temp\ipykernel_7080\939200695.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['Indicator and Influence'] = df_selected['Indicator'] + ": " + df_selected['Climate Influence']
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [6]:

df_selected

,Country,1992,1993,1994,1995,1996,1997,1998,1999,2000,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Indicator and Influence
0,"Afghanistan, Islamic Rep. of",25.320000,25.770000,26.160000,26.690000,27.230000,27.920000,28.990000,29.72000,30.780000,...,50.930000,54.320000,57.770000,60.71,60.710000,68.910000,69.480000,73.460000,73.420000,Artificial surfaces (including urban and assoc...
1,"Afghanistan, Islamic Rep. of",98.592188,98.699257,98.676899,98.754703,98.995163,99.108193,99.341081,99.75488,99.562156,...,100.167114,100.217018,100.058265,100.00,98.938261,98.413665,98.250357,98.491391,98.492743,Climate Altering Land Cover Index: Climate alt...
2,"Afghanistan, Islamic Rep. of",24035.390000,24035.410000,24035.440000,24045.960000,24044.980000,24053.620000,24056.200000,24193.03000,24253.130000,...,24799.260000,24797.690000,24762.140000,24761.90,24769.720000,24749.070000,24665.360000,24677.640000,24681.850000,Grassland: Climate regulating
3,"Afghanistan, Islamic Rep. of",5763.350000,5769.190000,5767.490000,5771.520000,5785.100000,5791.050000,5803.650000,5827.22000,5814.840000,...,5830.210000,5829.750000,5816.980000,5810.62,5748.280000,5709.290000,5699.120000,5709.300000,5709.440000,Herbaceous crops: Climate altering
4,"Afghanistan, Islamic Rep. of",261.230000,261.230000,261.230000,228.390000,207.970000,189.570000,185.480000,156.23000,150.230000,...,64.070000,64.070000,64.280000,64.28,64.310000,64.310000,64.310000,64.610000,64.600000,Inland water bodies: Climate regulating
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3016,Zimbabwe,27.580000,27.580000,27.580000,27.580000,27.610000,27.640000,27.920000,28.32000,28.370000,...,28.300000,28.250000,28.320000,28.32,28.170000,27.940000,27.910000,27.950000,27.990000,"Shrubs and/or herbaceous vegetation, aquatic o..."
3017,Zimbabwe,17.620000,17.620000,17.620000,17.610000,17.600000,17.600000,17.600000,17.93000,18.010000,...,18.260000,18.250000,18.230000,18.23,18.280000,18.280000,18.340000,18.310000,18.390000,Sparsely natural vegetated areas: Climate neutral
3018,Zimbabwe,92.750000,92.730000,92.710000,92.480000,92.420000,92.760000,93.240000,93.66000,94.420000,...,93.360000,93.200000,92.980000,92.97,91.960000,91.380000,90.630000,90.450000,90.370000,Terrestrial barren land: Climate neutral
3019,Zimbabwe,11097.520000,11097.110000,11096.780000,11089.700000,11104.180000,11146.530000,11136.560000,11092.84000,11137.750000,...,11280.560000,11288.060000,11323.870000,11323.76,11511.850000,11610.040000,11645.810000,11649.910000,11644.690000,Tree-covered areas: Climate regulating
3020,Zimbabwe,419.100000,413.740000,404.690000,403.750000,370.420000,360.550000,371.800000,360.90000,358.650000,...,334.100000,334.080000,333.750000,333.75,331.990000,330.720000,330.520000,330.560000,330.580000,Woody crops: Climate regulating

In [7]:
# Melt the dataframe to long format for manipulation
df_long = df_selected.melt(id_vars=['Country', 'Indicator and Influence'], var_name='Year', value_name='Value')

In [8]:
# Pivot the dataframe to get the desired structure
df_pivot = df_long.pivot_table(index=['Year', 'Country'], columns='Indicator and Influence', values='Value').reset_index()

In [9]:
df_pivot

Indicator and Influence,Year,Country,Artificial surfaces (including urban and associated areas): Climate altering,Climate Altering Land Cover Index: Climate altering,Grassland: Climate regulating,Herbaceous crops: Climate altering,Inland water bodies: Climate regulating,Mangroves: Climate regulating,Permanent snow and glaciers: Climate regulating,Shrub-covered areas: Climate regulating,"Shrubs and/or herbaceous vegetation, aquatic or regularly flooded: Climate regulating",Sparsely natural vegetated areas: Climate neutral,Terrestrial barren land: Climate neutral,Total Land Cover: Climate altering,Total Land Cover: Climate neutral,Total Land Cover: Climate regulating,Tree-covered areas: Climate regulating,Woody crops: Climate regulating
0,1992,"Afghanistan, Islamic Rep. of",25.32,98.592188,24035.39,5763.35,261.23,0.00,317.57,3350.55,5.82,4275.26,24963.00,NaN,NaN,NaN,1263.70,87.43
1,1992,Africa,NaN,91.832081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,290073.32,890573.61,1419131.0,NaN,NaN
2,1992,Albania,12.83,95.192830,401.78,985.60,55.67,0.00,0.00,323.11,6.50,32.98,52.04,NaN,NaN,NaN,786.80,213.15
3,1992,Algeria,79.55,94.061722,826.89,8368.58,165.53,0.00,0.00,2063.40,2.08,9113.08,208988.93,NaN,NaN,NaN,1534.52,588.74
4,1992,American Samoa,0.01,100.333125,1.48,2.61,1.36,0.16,0.00,1.05,0.00,0.02,0.00,NaN,NaN,NaN,8.21,5.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6955,2020,West Bank and Gaza,29.48,97.850456,40.11,83.56,19.11,0.00,0.00,30.71,0.00,116.37,116.57,NaN,NaN,NaN,35.43,153.32
6956,2020,Western Sahara,2.30,109.178549,0.67,3.41,7.61,0.00,0.00,0.00,0.00,19.62,26941.95,NaN,NaN,NaN,0.46,3.41
6957,2020,"Yemen, Rep. of",38.18,101.195241,164.11,1605.47,103.68,0.16,0.00,1608.93,0.87,5377.59,35827.99,NaN,NaN,NaN,471.81,407.61
6958,2020,Zambia,83.10,100.240566,3253.10,8278.47,1404.21,0.00,0.00,12441.95,2859.49,0.00,4.36,NaN,NaN,NaN,47154.83,84.96
6959,2020,Zimbabwe,65.65,99.187010,2406.87,13223.33,447.22,0.00,0.00,11018.83,27.99,18.39,90.37,NaN,NaN,NaN,11644.69,330.58

In [10]:
# Save the transformed dataset as a CSV file
output_file_path = './clean data/Land Cover Accounts Top 30 clean.csv'
df_pivot.to_csv(output_file_path, index=False)