In [1]:
import pandas as pd

C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [5]:
# Replace 'your_dataset.csv' with the path to your dataset
file_path = "./Datasets/Land Cover Accounts world only.csv"

In [6]:
# Load the dataset
data = pd.read_csv(file_path)

In [7]:
# Print the column names
print(data.columns.tolist())

['Country', 'ISO2', 'ISO3', 'Indicator', 'Unit', 'Source', 'CTS Code', 'CTS Name', 'CTS Full Descriptor', 'Climate Influence', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022']

In [10]:
# List of columns to keep
columns_to_keep = ['Indicator', 'Climate Influence', 
                   '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', 
                   '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', 
                   '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', 
                   '2016', '2017', '2018', '2019', '2020']

In [11]:
# Filter the DataFrame to keep only the specified columns
data_filtered = data[columns_to_keep]

# data_filtered now contains only the columns specified

In [12]:
data_filtered

,Indicator,Climate Influence,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Climate Altering Land Cover Index,Climate altering,9.682305e+01,9.706563e+01,9.687588e+01,9.744629e+01,9.760553e+01,9.784059e+01,9.814690e+01,9.882904e+01,...,1.001533e+02,1.000506e+02,1.000293e+02,1.000207e+02,100.00,9.987017e+01,9.978996e+01,9.974661e+01,9.967534e+01,9.968545e+01
1,Total Land Cover,Climate altering,1.838657e+06,1.862838e+06,1.859196e+06,1.870143e+06,1.873199e+06,1.877711e+06,1.883589e+06,1.896680e+06,...,1.924070e+06,1.958320e+06,1.957904e+06,1.957735e+06,1957330.56,1.954779e+06,1.953209e+06,1.952361e+06,1.950969e+06,1.951263e+06
2,Total Land Cover,Climate neutral,2.734703e+06,2.748924e+06,2.748969e+06,2.748697e+06,2.749042e+06,2.747808e+06,2.747063e+06,2.742785e+06,...,2.714678e+06,2.818462e+06,2.817674e+06,2.815385e+06,2815705.29,2.814918e+06,2.813688e+06,2.806427e+06,2.804217e+06,2.801653e+06
3,Total Land Cover,Climate regulating,8.476521e+06,8.576700e+06,8.580295e+06,8.569620e+06,8.566219e+06,8.562941e+06,8.557806e+06,8.548992e+06,...,8.563265e+06,8.674036e+06,8.675236e+06,8.677696e+06,8677781.52,8.681050e+06,8.683848e+06,8.691959e+06,8.695581e+06,8.698515e+06

In [14]:
# Melt the DataFrame to long format
long_format = data_filtered.melt(id_vars=['Indicator', 'Climate Influence'], 
                                 var_name='Year', 
                                 value_name='Value')

In [15]:
# Pivot to get the desired structure
pivoted_data = long_format.pivot_table(index='Year', 
                                       columns=['Indicator', 'Climate Influence'], 
                                       values='Value')

In [16]:

# Resetting the index to get 'Year' as a column
pivoted_data.reset_index(inplace=True)

In [17]:
pivoted_data

Indicator          Year Climate Altering Land Cover Index Total Land Cover  \
Climate Influence                        Climate altering Climate altering
0                  1992                         96.823051       1838657.48
1                  1993                         97.065634       1862838.29
2                  1994                         96.875877       1859196.32
3                  1995                         97.446286       1870143.38
4                  1996                         97.605525       1873199.48
5                  1997                         97.840594       1877710.57
6                  1998                         98.146901       1883588.84
7                  1999                         98.829043       1896680.22
8                  2000                         99.333508       1906842.47
9                  2001                         99.538201       1910772.15
10                 2002                         99.705436       1913981.79
11                 2003                         99.794634       1915694.96
12                 2004                        100.123592       1922009.12
13                 2005                        100.038019       1920366.79
14                 2006                        100.112281       1923282.37
15                 2007                        100.067460       1922421.62
16                 2008                        100.119702       1923424.94
17                 2009                        100.184813       1924676.63
18                 2010                        100.174347       1924475.04
19                 2011                        100.153300       1924070.20
20                 2012                        100.050552       1958320.12
21                 2013                        100.029340       1957904.41
22                 2014                        100.020658       1957734.77
23                 2015                        100.000000       1957330.56
24                 2016                         99.870171       1954779.20
25                 2017                         99.789957       1953208.78
26                 2018                         99.746607       1952360.62
27                 2019                         99.675341       1950968.58
28                 2020                         99.685449       1951262.77

Indicator
Climate Influence Climate neutral Climate regulating
0                      2734702.68         8476521.31
1                      2748924.00         8576699.88
2                      2748969.47         8580294.77
3                      2748697.25         8569620.16
4                      2749042.30         8566219.41
5                      2747808.16         8562940.73
6                      2747063.27         8557805.76
7                      2742785.43         8548992.43
8                      2736872.18         8548069.73
9                      2735269.46         8545744.92
10                     2733159.62         8544640.55
11                     2732274.72         8543818.45
12                     2725075.04         8544699.51
13                     2723774.18         8547645.23
14                     2722740.06         8555991.74
15                     2720452.58         8559142.08
16                     2718871.87         8559717.30
17                     2717005.15         8560338.01
18                     2715743.71         8561797.41
19                     2714677.76         8563264.89
20                     2818461.95         8674035.98
21                     2817674.22         8675235.74
22                     2815385.24         8677696.42
23                     2815705.29         8677781.52
24                     2814917.87         8681050.33
25                     2813688.05         8683847.96
26                     2806427.31         8691959.11
27                     2804217.15         8695581.12
28                     2801653.24         8698514.93

In [18]:
pivoted_data.columns = [' '.join(col).strip() for col in pivoted_data.columns.values]

In [19]:
# Specify the file path and name for your new CSV file
output_file_path = "./clean data/Land Cover Accounts_cleaned.csv"

# Save the DataFrame to a CSV file
pivoted_data.to_csv(output_file_path, index=False)